Repository openrewrite/rewrite-python, pull requests merged in 2025-01, with the labels that each got.

#104 Tabs and Indents visitor
  rewrite/rewrite/java/support_types.py
  rewrite/rewrite/python/format/auto_format.py
  rewrite/rewrite/python/format/tabs_and_indents_visitor.py
  rewrite/rewrite/python/utils/__init__.py
  rewrite/rewrite/python/utils/tree_visiting_printer.py
  rewrite/rewrite/visitor.py
  rewrite/tests/python/all/format/tabs_and_indents_visitor_test.py
Labels: enhancement

#121 Explaining PyCharm setup
  README.md
Labels: documentation

#124 Fix for spaces around nested parenthesis
  rewrite/rewrite/python/format/spaces_visitor.py
  rewrite/tests/python/all/format/spaces/parenthesis_spaces_test.py
Labels: bug

#131 While loop condition spaces
  rewrite/rewrite/python/format/spaces_visitor.py
  rewrite/tests/python/all/format/spaces/loops_space_test.py
Labels: bug, enhancement

#130 Add an end-to-end test for the formatter
  rewrite/tests/python/all/format/full_formatter_test.py
Labels: enhancement

#128 `PythonPrinter` in Python
  rewrite/rewrite/python/printer.py
  rewrite/rewrite/python/tree.py
  rewrite/rewrite/test.py
  rewrite/rewrite/tree.py
Labels: enhancement

#132 Add method parameters alignment, fixes to spaces visitor, and extended end2end tests
  rewrite-python/src/main/java/org/openrewrite/python/style/IntelliJ.java
  rewrite-python/src/main/java/org/openrewrite/python/style/TabsAndIndentsStyle.java
  rewrite/rewrite/python/format/spaces_visitor.py
  rewrite/rewrite/python/format/tabs_and_indents_visitor.py
  rewrite/rewrite/python/style.py
  rewrite/rewrite/visitor.py
  rewrite/tests/python/all/format/full_formatter_test.py
  rewrite/tests/python/all/format/spaces/import_spaces_test.py
  rewrite/tests/python/all/format/spaces/method_declaration_spaces_test.py
  rewrite/tests/python/all/format/tabs_and_indents_visitor_test.py
Labels: bug, enhancement

#115 Fix and extra tests for literals
  rewrite/rewrite/python/format/tabs_and_indents_visitor.py
  rewrite/tests/python/all/format/tabs_and_indents_visitor_test.py
Labels: parser-python

#129 Add fix for operators
  rewrite/rewrite/python/format/spaces_visitor.py
  rewrite/tests/python/all/format/spaces/around_operator_test.py
  rewrite/tests/python/all/format/spaces/method_declaration_spaces_test.py
Labels: bug, enhancement

#133 Fix spaces around keyvalues in dict comprehensions
  rewrite/rewrite/python/format/spaces_visitor.py
  rewrite/tests/python/all/format/spaces/comprehension_spaces_test.py
Labels: bug
